In [ ]:
t=["abc","adc"]
#t.append("acd")
a=list(("adc","gvf"))
t.extend(a)
print(t)

['abc', 'adc', 'adc', 'gvf']


In [ ]:
import numpy as np
a=np.array([[1,3],[2,3]])
print(a)
print(type(a))
print(a.shape)
#b=np.array([1,3],dytpe=np.float64)
#print(b)
#print(type(b))
c=np.ones(2)
print(c)
d=np.zeros(3)
print(d)
e=np.random.random((3,2))#returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).
print(e)
f=np.ones((4,3,2))
print(f)
g=np.zeros((4,3,2))
print(g)
h=np.full((2,2),7)# return 2*2 ary with full of 7
print(h)
i=np.eye(2) #The numpy.eye() function in NumPy returns a 2-D array with ones on the diagonal and zeros elsewhere.
print(i)

j=np.linspace(0.,1.,num=5)# range and how many elements
print(j)
h=np.linspace(0,1,5)
print(h)

k=np.array([1,2,3,4,5])
print(k)
m=np.array([[1,2,3],[3,4,5]])
print(m)
print(m[0:1,0])
n=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(n)
print(n[1:3,1:3])
o=np.array([[1,2,3,5],[3,4,5,6],[3,4,5,6]])
print(o)
rr1=o[1, :]
rr2=o[1:3, :]
rr3=o[[1], :]
print(rr1,rr1.shape)
print(rr2,rr2.shape)
print(rr2,rr2.shape)
cr1=o[:,1]
cr2=o[:,1:2]
print(cr1,cr1.shape)
print(cr2,cr2.shape)




[[1 3]
 [2 3]]
<class 'numpy.ndarray'>
(2, 2)
[1. 1.]
[0. 0. 0.]
[[0.68470524 0.95352097]
 [0.35831719 0.82875664]
 [0.71953315 0.02681233]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]
[1 2 3 4 5]
[[1 2 3]
 [3 4 5]]
[1]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[4 5]
 [5 6]]
[[1 2 3 5]
 [3 4 5 6]
 [3 4 5 6]]
[3 4 5 6] (4,)
[[3 4 5 6]
 [3 4 5 6]] (2, 4)
[[3 4 5 6]
 [3 4 5 6]] (2, 4)
[2 4 4] (3,)
[[2]
 [4]
 [4]] (3, 1)
