In [ ]:
import numpy as np
x=np.array([[1,2,3],[2,3,4],[4,5,6],[5,6,7]])
print(x)
print(x.shape)
b=np.array([0,2,0,1])
print(x[np.arange(4),b])

#bool

a=np.array([1,2,3,44,54,5])#arg =index
print(np.argmax(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a>= a[np.argmax(a)])[0])

h=[0]
h=np.append(h,[1,2,3,4])
print(h)
v=np.delete(h,[2,3])
print(v)

f=np.array([[1,2,3],[44,54,5]])#arg =index
print(np.where(f>2)[0])

g=np.array([[1,3,2],[3,5,2],[5,4,2]])
y=np.sort(g,axis=1,kind="quicksort")# axis=0=row,1=col
print(y)
y1=np.sort(g,axis=0,kind="quicksort")# axis=0=row,1=col
print(y1)

z=np.array([[1,2],[2,3],[3,4]])
print(np.max(z))

w=np.array([[1],[2],[3]])
print(w)
print(w.shape)

c=w.squeeze()#removes the unwanted space
print(c)
print(c.shape)

d=w.reshape(-1)
print(d)
print(d.shape)

i=np.array([[1,2,3],[1,3,4]])+np.array([1,4,5]) #broadcasting =match with the highest row ANd col (i.e) other [1,4,5] id created and added (ANY ONE ROW ORCOL IS TRIED TO MATCH)
print(i)

#J=np.array([[1,2,3],[1,3]])+np.array([1,4,5])   [error]
#print(J)

[[1 2 3]
 [2 3 4]
 [4 5 6]
 [5 6 7]]
(4, 3)
[1 4 4 6]
4
[0 1 2 5 3 4]
[4 3 5 2 1 0]
[3 4]
[4]
[0 1 2 3 4]
[0 1 4]
[0 1 1 1]
[[1 2 3]
 [2 3 5]
 [2 4 5]]
[[1 3 2]
 [3 4 2]
 [5 5 2]]
4
[[1]
 [2]
 [3]]
(3, 1)
[1 2 3]
(3,)
[1 2 3]
(3,)
[[2 6 8]
 [2 7 9]]
